# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/www/cpp_lua/cpplua0.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/www/cpp_lua/cpplua0.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/www/cpp_lua/cpplua0.2/CMakeFiles /data/www/cpp_lua/cpplua0.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/www/cpp_lua/cpplua0.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppLua

# Build rule for target.
CppLua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CppLua
.PHONY : CppLua

# fast build rule for target.
CppLua/fast:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/build
.PHONY : CppLua/fast

luafunction.o: luafunction.cpp.o
.PHONY : luafunction.o

# target to build an object file
luafunction.cpp.o:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luafunction.cpp.o
.PHONY : luafunction.cpp.o

luafunction.i: luafunction.cpp.i
.PHONY : luafunction.i

# target to preprocess a source file
luafunction.cpp.i:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luafunction.cpp.i
.PHONY : luafunction.cpp.i

luafunction.s: luafunction.cpp.s
.PHONY : luafunction.s

# target to generate assembly for a file
luafunction.cpp.s:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luafunction.cpp.s
.PHONY : luafunction.cpp.s

luaobject.o: luaobject.cpp.o
.PHONY : luaobject.o

# target to build an object file
luaobject.cpp.o:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luaobject.cpp.o
.PHONY : luaobject.cpp.o

luaobject.i: luaobject.cpp.i
.PHONY : luaobject.i

# target to preprocess a source file
luaobject.cpp.i:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luaobject.cpp.i
.PHONY : luaobject.cpp.i

luaobject.s: luaobject.cpp.s
.PHONY : luaobject.s

# target to generate assembly for a file
luaobject.cpp.s:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luaobject.cpp.s
.PHONY : luaobject.cpp.s

luastate.o: luastate.cpp.o
.PHONY : luastate.o

# target to build an object file
luastate.cpp.o:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luastate.cpp.o
.PHONY : luastate.cpp.o

luastate.i: luastate.cpp.i
.PHONY : luastate.i

# target to preprocess a source file
luastate.cpp.i:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luastate.cpp.i
.PHONY : luastate.cpp.i

luastate.s: luastate.cpp.s
.PHONY : luastate.s

# target to generate assembly for a file
luastate.cpp.s:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luastate.cpp.s
.PHONY : luastate.cpp.s

luatable.o: luatable.cpp.o
.PHONY : luatable.o

# target to build an object file
luatable.cpp.o:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luatable.cpp.o
.PHONY : luatable.cpp.o

luatable.i: luatable.cpp.i
.PHONY : luatable.i

# target to preprocess a source file
luatable.cpp.i:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luatable.cpp.i
.PHONY : luatable.cpp.i

luatable.s: luatable.cpp.s
.PHONY : luatable.s

# target to generate assembly for a file
luatable.cpp.s:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/luatable.cpp.s
.PHONY : luatable.cpp.s

stackcollectible.o: stackcollectible.cpp.o
.PHONY : stackcollectible.o

# target to build an object file
stackcollectible.cpp.o:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/stackcollectible.cpp.o
.PHONY : stackcollectible.cpp.o

stackcollectible.i: stackcollectible.cpp.i
.PHONY : stackcollectible.i

# target to preprocess a source file
stackcollectible.cpp.i:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/stackcollectible.cpp.i
.PHONY : stackcollectible.cpp.i

stackcollectible.s: stackcollectible.cpp.s
.PHONY : stackcollectible.s

# target to generate assembly for a file
stackcollectible.cpp.s:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/stackcollectible.cpp.s
.PHONY : stackcollectible.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/CppLua.dir/build.make CMakeFiles/CppLua.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CppLua"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... luafunction.o"
	@echo "... luafunction.i"
	@echo "... luafunction.s"
	@echo "... luaobject.o"
	@echo "... luaobject.i"
	@echo "... luaobject.s"
	@echo "... luastate.o"
	@echo "... luastate.i"
	@echo "... luastate.s"
	@echo "... luatable.o"
	@echo "... luatable.i"
	@echo "... luatable.s"
	@echo "... stackcollectible.o"
	@echo "... stackcollectible.i"
	@echo "... stackcollectible.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

